version: "2"

volumes:
  redis:

services:
  server:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    environment:
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}
      - ALLOW_DEFAULTS
      - PUBLIC_PATH
    ports:
      - "127.0.0.1:${CONTAINER_PORT:-8000}:8000"
    volumes:
      - ${ETC_PATH:-/etc}:/etc/asu:rw
    depends_on:
      - redis

  worker:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    command: rqworker
    environment:
      - CONTAINER_HOST=unix://${CONTAINER_SOCK}
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}
    volumes:
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
      - $CONTAINER_SOCK:$CONTAINER_SOCK:rw
      - ${ETC_PATH:-/etc}:/etc/asu:rw
    depends_on:
      - redis

  worker2:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    command: rqworker
    environment:
      - CONTAINER_HOST=unix://${CONTAINER_SOCK}
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}
    volumes:
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
      - $CONTAINER_SOCK:$CONTAINER_SOCK:rw
      - ${ETC_PATH:-/etc}:/etc/asu:rw
    depends_on:
      - redis

  redis:
    image: "docker.io/redis:alpine"
    restart: always
    volumes:
      - redis:/data/:rw
